# /docker-compose-test.yml
version: '3'

services:
  integration:
    build: 
      context: .
      dockerfile: dockerfile-build
    environment:
      - CONNECTION_STRING=Server=db;Database=todosdb;Uid=root;Pwd=password;SslMode=None;      
    entrypoint: bash /app/wait_for_it.sh db:3306 -t 0 -- dotnet test
    depends_on:
      - db
  db:
    #image: mysql/mysql-server
    build: 
      context: .
      dockerfile: dockerfile-custom-mysql
    ports:
      - 3306:3306
    # Start the container with a todosdb, and password as the root users password
    environment: 
      - MYSQL_DATABASE=todosdb
      - MYSQL_ROOT_PASSWORD=password
