# /docker-compose-test.yml
version: '3'

services:
  integration:
    build: 
      context: .
      dockerfile: dockerfile-build
    environment:
      - CONNECTION_STRING=Location=db;Data Source=todosdb;User ID=root;Password=password;Port=3306
    entrypoint: dotnet test ./src/MySqlDriverCs.Core.Tests/MySqlDriverCs.Core.Tests.csproj
    depends_on:
      - db
  db:
    image: mysql/mysql-server
    #command: mysqld --default-authentication-plugin=mysql_native_password --skip-mysqlx
    #entrypoint: ['/entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
    #command: mysql -uroot -ppassword -e "ALTER USER root@localhost IDENTIFIED WITH mysql_native_password BY 'password';"
    restart: always
    ports:
      - 3306:3306
    # Start the container with a todosdb, and password as the root users password
    environment: 
      - MYSQL_DATABASE=todosdb
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
