FROM mcr.microsoft.com/dotnet/core/sdk:3.1 as netcore_mysql_client
RUN uname -o
RUN apt-get -y update &&\
    apt-get -y upgrade &&\
	apt-get install -y --force-yes default-libmysqlclient-dev &&\
	apt-get clean

FROM netcore_mysql_client
WORKDIR /app
COPY MySqlDriverCs.Core.sln .
RUN mkdir src
COPY ./src ./src
# restore nugets
RUN dotnet restore MySqlDriverCs.Core.sln

