# /docker-compose-test.yml
version: '3'

services:
  integration:
    build: 
      context: .
      dockerfile: dockerfile-build
    environment:
      - CONNECTION_STRING=Location=db;Data Source=todosdb;User ID=root;Password=password;Port=3307
#    entrypoint: bash /app/wait_for_it.sh db:3306 -t 0 -- dotnet test
    entrypoint: dotnet test ./src/MySqlDriverCs.Core.Tests/MySqlDriverCs.Core.Tests.csproj
    depends_on:
      - db
  db:
    image: mysql
    ports:
      - 3307:3306
    # Start the container with a todosdb, and password as the root users password
    environment: 
      - MYSQL_DATABASE=todosdb
      - MYSQL_ROOT_PASSWORD=password
