using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace MySQLDriverCS
{
    /// <summary>
    /// Data taken from https://dev.mysql.com/doc/internals/en/charsets.html
    /// </summary>
    internal static class CollationEntries
    {
        public static CollationEntry[] Entries = new[]
            {
                new CollationEntry("64", "armscii8", "armscii8_bin", " ??", "1"),
                new CollationEntry("32", "armscii8", "armscii8_general_ci", "Yes", "1"),
                new CollationEntry("65", "ascii", "ascii_bin", " ??", "1"),
                new CollationEntry("11", "ascii", "ascii_general_ci", "Yes", "1"),
                new CollationEntry("84", "big5", "big5_bin", " ??", "1"),
                new CollationEntry("1", "big5", "big5_chinese_ci", "Yes", "1"),
                new CollationEntry("63", "binary", "binary", "Yes", "1"),
                new CollationEntry("66", "cp1250", "cp1250_bin", " ??", "1"),
                new CollationEntry("44", "cp1250", "cp1250_croatian_ci", " ??", "1"),
                new CollationEntry("34", "cp1250", "cp1250_czech_cs", " ??", "2"),
                new CollationEntry("26", "cp1250", "cp1250_general_ci", "Yes", "1"),
                new CollationEntry("50", "cp1251", "cp1251_bin", " ??", "1"),
                new CollationEntry("14", "cp1251", "cp1251_bulgarian_ci", " ??", "1"),
                new CollationEntry("52", "cp1251", "cp1251_general_cs", " ??", "1"),
                new CollationEntry("23", "cp1251", "cp1251_ukrainian_ci", " ??", "1"),
                new CollationEntry("51", "cp1251", "cp1251_general_ci", "Yes", "1"),
                new CollationEntry("67", "cp1256", "cp1256_bin", " ??", "1"),
                new CollationEntry("57", "cp1256", "cp1256_general_ci", "Yes", "1"),
                new CollationEntry("58", "cp1257", "cp1257_bin", " ??", "1"),
                new CollationEntry("29", "cp1257", "cp1257_lithuanian_ci", " ??", "1"),
                new CollationEntry("59", "cp1257", "cp1257_general_ci", "Yes", "1"),
                new CollationEntry("80", "cp850", "cp850_bin", " ??", "1"),
                new CollationEntry("4", "cp850", "cp850_general_ci", "Yes", "1"),
                new CollationEntry("81", "cp852", "cp852_bin", " ??", "1"),
                new CollationEntry("40", "cp852", "cp852_general_ci", "Yes", "1"),
                new CollationEntry("68", "cp866", "cp866_bin", " ??", "1"),
                new CollationEntry("36", "cp866", "cp866_general_ci", "Yes", "1"),
                new CollationEntry("96", "cp932", "cp932_bin", " ??", "1"),
                new CollationEntry("95", "cp932", "cp932_japanese_ci", "Yes", "1"),
                new CollationEntry("69", "Dec-08", "dec8_bin", " ??", "1"),
                new CollationEntry("3", "Dec-08", "dec8_swedish_ci", "Yes", "1"),
                new CollationEntry("98", "eucjpms", "eucjpms_bin", " ??", "1"),
                new CollationEntry("97", "eucjpms", "eucjpms_japanese_ci", "Yes", "1"),
                new CollationEntry("85", "euckr", "euckr_bin", " ??", "1"),
                new CollationEntry("19", "euckr", "euckr_korean_ci", "Yes", "1"),
                new CollationEntry("86", "gb2312", "gb2312_bin", " ??", "1"),
                new CollationEntry("24", "gb2312", "gb2312_chinese_ci", "Yes", "1"),
                new CollationEntry("87", "gbk", "gbk_bin", " ??", "1"),
                new CollationEntry("28", "gbk", "gbk_chinese_ci", "Yes", "1"),
                new CollationEntry("93", "geostd8", "geostd8_bin", " ??", "1"),
                new CollationEntry("92", "geostd8", "geostd8_general_ci", "Yes", "1"),
                new CollationEntry("70", "greek", "greek_bin", " ??", "1"),
                new CollationEntry("25", "greek", "greek_general_ci", "Yes", "1"),
                new CollationEntry("71", "hebrew", "hebrew_bin", " ??", "1"),
                new CollationEntry("16", "hebrew", "hebrew_general_ci", "Yes", "1"),
                new CollationEntry("72", "hp8", "hp8_bin", " ??", "1"),
                new CollationEntry("6", "hp8", "hp8_english_ci", "Yes", "1"),
                new CollationEntry("73", "keybcs2", "keybcs2_bin", " ??", "1"),
                new CollationEntry("37", "keybcs2", "keybcs2_general_ci", "Yes", "1"),
                new CollationEntry("74", "koi8r", "koi8r_bin", " ??", "1"),
                new CollationEntry("7", "koi8r", "koi8r_general_ci", "Yes", "1"),
                new CollationEntry("75", "koi8u", "koi8u_bin", " ??", "1"),
                new CollationEntry("22", "koi8u", "koi8u_general_ci", "Yes", "1"),
                new CollationEntry("47", "latin1", "latin1_bin", " ??", "1"),
                new CollationEntry("15", "latin1", "latin1_danish_ci", " ??", "1"),
                new CollationEntry("48", "latin1", "latin1_general_ci", " ??", "1"),
                new CollationEntry("49", "latin1", "latin1_general_cs", " ??", "1"),
                new CollationEntry("5", "latin1", "latin1_german1_ci", " ??", "1"),
                new CollationEntry("31", "latin1", "latin1_german2_ci", " ??", "2"),
                new CollationEntry("94", "latin1", "latin1_spanish_ci", " ??", "1"),
                new CollationEntry("8", "latin1", "latin1_swedish_ci", "Yes", "1"),
                new CollationEntry("77", "latin2", "latin2_bin", " ??", "1"),
                new CollationEntry("27", "latin2", "latin2_croatian_ci", " ??", "1"),
                new CollationEntry("2", "latin2", "latin2_czech_cs", " ??", "4"),
                new CollationEntry("21", "latin2", "latin2_hungarian_ci", " ??", "1"),
                new CollationEntry("9", "latin2", "latin2_general_ci", "Yes", "1"),
                new CollationEntry("78", "latin5", "latin5_bin", " ??", "1"),
                new CollationEntry("30", "latin5", "latin5_turkish_ci", "Yes", "1"),
                new CollationEntry("79", "latin7", "latin7_bin", " ??", "1"),
                new CollationEntry("20", "latin7", "latin7_estonian_cs", " ??", "1"),
                new CollationEntry("42", "latin7", "latin7_general_cs", " ??", "1"),
                new CollationEntry("41", "latin7", "latin7_general_ci", "Yes", "1"),
                new CollationEntry("43", "macce", "macce_bin", " ??", "1"),
                new CollationEntry("38", "macce", "macce_general_ci", "Yes", "1"),
                new CollationEntry("53", "macroman", "macroman_bin", " ??", "1"),
                new CollationEntry("39", "macroman", "macroman_general_ci", "Yes", "1"),
                new CollationEntry("88", "sjis", "sjis_bin", " ??", "1"),
                new CollationEntry("13", "sjis", "sjis_japanese_ci", "Yes", "1"),
                new CollationEntry("82", "swe7", "swe7_bin", " ??", "1"),
                new CollationEntry("10", "swe7", "swe7_swedish_ci", "Yes", "1"),
                new CollationEntry("89", "tis620", "tis620_bin", " ??", "1"),
                new CollationEntry("18", "tis620", "tis620_thai_ci", "Yes", "4"),
                new CollationEntry("90", "ucs2", "ucs2_bin", " ??", "1"),
                new CollationEntry("138", "ucs2", "ucs2_czech_ci", " ??", "8"),
                new CollationEntry("139", "ucs2", "ucs2_danish_ci", " ??", "8"),
                new CollationEntry("145", "ucs2", "ucs2_esperanto_ci", " ??", "8"),
                new CollationEntry("134", "ucs2", "ucs2_estonian_ci", " ??", "8"),
                new CollationEntry("146", "ucs2", "ucs2_hungarian_ci", " ??", "8"),
                new CollationEntry("129", "ucs2", "ucs2_icelandic_ci", " ??", "8"),
                new CollationEntry("130", "ucs2", "ucs2_latvian_ci", " ??", "8"),
                new CollationEntry("140", "ucs2", "ucs2_lithuanian_ci", " ??", "8"),
                new CollationEntry("144", "ucs2", "ucs2_persian_ci", " ??", "8"),
                new CollationEntry("133", "ucs2", "ucs2_polish_ci", " ??", "8"),
                new CollationEntry("131", "ucs2", "ucs2_romanian_ci", " ??", "8"),
                new CollationEntry("143", "ucs2", "ucs2_roman_ci", " ??", "8"),
                new CollationEntry("141", "ucs2", "ucs2_slovak_ci", " ??", "8"),
                new CollationEntry("132", "ucs2", "ucs2_slovenian_ci", " ??", "8"),
                new CollationEntry("142", "ucs2", "ucs2_spanish2_ci", " ??", "8"),
                new CollationEntry("135", "ucs2", "ucs2_spanish_ci", " ??", "8"),
                new CollationEntry("136", "ucs2", "ucs2_swedish_ci", " ??", "8"),
                new CollationEntry("137", "ucs2", "ucs2_turkish_ci", " ??", "8"),
                new CollationEntry("128", "ucs2", "ucs2_unicode_ci", " ??", "8"),
                new CollationEntry("35", "ucs2", "ucs2_general_ci", "Yes", "1"),
                new CollationEntry("91", "ujis", "ujis_bin", " ??", "1"),
                new CollationEntry("12", "ujis", "ujis_japanese_ci", "Yes", "1"),
                new CollationEntry("83", "utf8", "utf8_bin", " ??", "1"),
                new CollationEntry("202", "utf8", "utf8_czech_ci", " ??", "8"),
                new CollationEntry("203", "utf8", "utf8_danish_ci", " ??", "8"),
                new CollationEntry("209", "utf8", "utf8_esperanto_ci", " ??", "8"),
                new CollationEntry("198", "utf8", "utf8_estonian_ci", " ??", "8"),
                new CollationEntry("210", "utf8", "utf8_hungarian_ci", " ??", "8"),
                new CollationEntry("193", "utf8", "utf8_icelandic_ci", " ??", "8"),
                new CollationEntry("194", "utf8", "utf8_latvian_ci", " ??", "8"),
                new CollationEntry("204", "utf8", "utf8_lithuanian_ci", " ??", "8"),
                new CollationEntry("208", "utf8", "utf8_persian_ci", " ??", "8"),
                new CollationEntry("197", "utf8", "utf8_polish_ci", " ??", "8"),
                new CollationEntry("195", "utf8", "utf8_romanian_ci", " ??", "8"),
                new CollationEntry("207", "utf8", "utf8_roman_ci", " ??", "8"),
                new CollationEntry("205", "utf8", "utf8_slovak_ci", " ??", "8"),
                new CollationEntry("196", "utf8", "utf8_slovenian_ci", " ??", "8"),
                new CollationEntry("206", "utf8", "utf8_spanish2_ci", " ??", "8"),
                new CollationEntry("199", "utf8", "utf8_spanish_ci", " ??", "8"),
                new CollationEntry("200", "utf8", "utf8_swedish_ci", " ??", "8"),
                new CollationEntry("201", "utf8", "utf8_turkish_ci", " ??", "8"),
                new CollationEntry("192", "utf8", "utf8_unicode_ci", " ??", "8"),
                new CollationEntry("33", "utf8", "utf8_general_ci", "Yes", "1"),
            };

        public static Encoding TryGetEncoding(int collationId)
        {
            return Entries.FirstOrDefault(x => x.CollationId == collationId)?.Encoding;
        }
        public static CollationEntry TryGet(int collationId)
        {
            return Entries.FirstOrDefault(x => x.CollationId == collationId);
        }
    }
}
